sonar.projectKey=Echo
sonar.projectName=Echo
sonar.projectVersion=1.0
sonar.language=swift

sonar.exclusions=Pods/**
sonar.exclusions=scripts/**
sonar.exclusions=build/**
sonar.exclusions=fastlane/**
sonar.exclusions=common/**

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
sonar.html.file.suffixes=-
sonar.css.file.suffixes=-
