name: iOS build CI

on:
  push:
    branches:
      - master  # or 'main' if that's your default branch name
  pull_request:
    branches:
      - '*'  # This will run on pull requests targeting any branch

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build for iOS
      run: |
        xcodebuild clean build -scheme Echo -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -sdk iphonesimulator

    - name: Run tests
      run: |
        xcodebuild test -scheme Echo -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -sdk iphonesimulator

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
